

spring:
  application:
    name: myApp
  datasource:
    #url: jdbc:mysql://localhost:3306/students
    #username: root
    #password : GALGALLO10
    url: jdbc:mysql://mysql.galgallo-test-space.svc.cluster.local:3306/sampledb
    username : galgallo_username
    password: connection_password
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


server:
  error:
    include-message: always

