apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myApp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myApp
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization